### ISSUE TITLE
Setup @merrymerkle.com email

### ISSUE THREAD

**Issue by shazow** [MerryMerkle/merrymerkle.github.io#14]
- [x] Set MX records on DNS: 10 in1-smtp.messagingengine.com, 20 in2-smtp.messagingengine.com
- [x] TXT/CName confirmation
- [x] Confirm email works

**Comment by shazow** [comment]
@Shrugs MX records are ready. Ping if/when you need me to do TXT or whatever.

**Comment by shrugs** [comment]
CNAMES

```
fm1._domainkey.merrymerkle.com -> fm1.merrymerkle.com.dkim.fmhosted.com
fm2._domainkey.merrymerkle.com -> fm2.merrymerkle.com.dkim.fmhosted.com
fm3._domainkey.merrymerkle.com -> fm3.merrymerkle.com.dkim.fmhosted.com
```

TXT

```
merrymerkle.com -> "v=spf1 include:spf.messagingengine.com ?all"
```

**Comment by shazow** [comment]
This is not done yet.

**Comment by shazow** [comment]
Now it is done. @Shrugs Added the records, re-open if there are still issues.
